package main

var (
	GAME_STAGES = []Stage{
		Stage{
			text: "CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE",
			text_speed: 0.05,
			is_battle: false,
			level: 0,
			p1: 0,
			e1: 3,
			p2: 1,
			e2: 2,
			lose_stage: 0,
			font: 1,
		},
		Stage{
			text: "Awawawawawa!",
			text_speed: 0.05,
			is_battle: false,
			level: 0,
			p1: 0,
			e1: 3,
			p2: 1,
			e2: 4,
			lose_stage: 0,
			font: 2,
		},
		Stage{
			text: "So cute I just want to crush you to death",
			text_speed: 0.05,
			is_battle: false,
			level: 0,
			p1: 0,
			e1: 4,
			p2: 1,
			e2: 1,
			lose_stage: 0,
			font: 1,
		},
		Stage{
			text: "awawawawawa...",
			text_speed: 0.05,
			is_battle: false,
			level: 0,
			p1: 0,
			e1: 4,
			p2: 1,
			e2: 0,
			lose_stage: 0,
			font: 2,
		},
		Stage{
			text: "",
			text_speed: 0.05,
			is_battle: true,
			level: 0,
			p1: 0,
			e1: 4,
			p2: 1,
			e2: 0,
			lose_stage: 0,
		},
		Stage{
			text: "Hey Dizzy do you want to be my second wife?",
			text_speed: 0.05,
			is_battle: false,
			level: 0,
			p1: 0,
			e1: 3,
			p2: 2,
			e2: 2,
			lose_stage: 0,
			font: 1,
		},
		Stage{
			text: "This is now a self defense situation",
			text_speed: 0.05,
			is_battle: false,
			level: 0,
			p1: 0,
			e1: 0,
			p2: 2,
			e2: 4,
			lose_stage: 0,
			font: 3,
		},
		Stage{
			text: "",
			text_speed: 0.05,
			is_battle: true,
			level: 1,
			p1: 0,
			e1: 4,
			p2: 1,
			e2: 0,
			lose_stage: 5,
		},
		Stage{
			text: "Hey Loomer",
			text_speed: 0.05,
			is_battle: false,
			level: 0,
			p1: 0,
			e1: 2,
			p2: 3,
			e2: 2,
			lose_stage: 0,
			font: 4,
		},
		Stage{
			text: "Hey, whats with the face?",
			text_speed: 0.05,
			is_battle: false,
			level: 0,
			p1: 0,
			e1: 2,
			p2: 3,
			e2: 3,
			lose_stage: 0,
			font: 1,
		},
		Stage{
			text: "I burned down one of your kitchens",
			text_speed: 0.05,
			is_battle: false,
			level: 0,
			p1: 0,
			e1: 2,
			p2: 3,
			e2: 4,
			lose_stage: 0,
			font: 4,
		},
		Stage{
			text: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
			text_speed: 0.02,
			is_battle: false,
			level: 0,
			p1: 0,
			e1: 0,
			p2: 3,
			e2: 4,
			lose_stage: 0,
			font: 1,
		},
		Stage{
			text: "",
			text_speed: 0.05,
			is_battle: true,
			level: 2,
			p1: 0,
			e1: 4,
			p2: 1,
			e2: 0,
			lose_stage: 8,
		},
		Stage{
			text: "And thats the story of how Lumi killed all her friends.",
			text_speed: 0.05,
			is_battle: false,
			level: 2,
			p1: 0,
			e1: 2,
			p2: 0,
			e2: 2,
			lose_stage: 0,
		},
	}
)
